import type { Metadata } from "next";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import VLibras from "./components/vlibras";

export const metadata: Metadata = {
  title: "Portal Connect - Maylon",
  description: "Generated by create next app",
};

const gaId = process.env.NEXT_PUBLIC_GA_ID || "G-4R88G65G1X";
const enableAnalytics =
  process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === "true" ||
  process.env.NODE_ENV === "production";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
        <VLibras />
      </body>
      {enableAnalytics ? <GoogleAnalytics gaId={gaId} /> : null}
    </html>
  );
}
