import type { Metadata } from "next";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import VLibras from "./components/vlibras";

export const metadata: Metadata = {
  title: "Portal Connect - Maylon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
        <VLibras />
      </body>
      <GoogleAnalytics gaId="G-4R88G65G1X" />
    </html>
  );
}